---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: edx-platform-ci-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: eks-poc/edx-platform
      # this should also point to runner image hosted under edX's dockerhub
      image: openedx/edx-platform-ci-runner
      resources:
        requests:
          cpu: "2.0"
          memory: "4Gi"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: edx-platform-ci-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: edx-platform-ci-runner-deployment
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 72
#  scaleUpTriggers:
#    - githubEvent: {}
#      duration: "20m"
  metrics:
#  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
#    repositoryNames:
#    - eks-poc/edx-platform
#  - type: PercentageRunnersBusy
#    scaleUpThreshold: "0.75"
#    scaleDownThreshold: "0.3"
#    scaleUpAdjustment: 2
#    scaleDownAdjustment: 1
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created", "rerequested"]
        status: "queued"
    amount: 1
    duration: "10m"
#  - githubEvent:
#      pullRequest:
#        types: ["opened", "synchronize", "reopened"]
#    amount: 12
#    duration: "20m"
#  - githubEvent:
#      push:
#    amount: 12
#    duration: "20m"
