# authSecret:
#   create: true
#   github_app_id:
#   github_app_installation_id:
#   github_app_private_key: |
#

syncPeriod: 2m
githubWebhookServer:
  enabled: true
  syncPeriod: 2m
  service:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
